namespace AppCore.Interfaces
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using AppCore.DTOs;
    using AppCore.Enums;

    public interface ITaskService
    {
        /// <summary>
        ///     Create a new task
        /// </summary>
        /// <param name="itemDto">Task DTO without id, because the id will be autogenerated</param>
        /// <returns>Updated task DTO with new id value</returns>
        Task< TaskItemDto > CreateTaskAsync( TaskItemDto itemDto );

        /// <summary>
        ///     Get a list of task with have the provided Status
        /// </summary>
        /// <param name="status">Status of the Tasks you want a list of</param>
        /// <returns>List of Task with have the required status</returns>
        Task< List< TaskItemDto > > GetAllTaskByStatusAsync( Status status );

        /// <summary>
        ///     Returns a Task from by its Id
        /// </summary>
        /// <param name="id">id of Task to return</param>
        /// <returns>Returns a Task DTO</returns>
        Task< TaskItemDto > GetTaskByIdAsync( int id );

        /// <summary>
        ///     Remove a Task
        /// </summary>
        /// <param name="id">Task id to remove</param>
        /// <returns>A bool stating if the record was deleted sucesfully</returns>
        Task< bool > RemoveTaskAsync( int id );

        /// <summary>
        ///     Updates a Task
        /// </summary>
        /// <param name="itemDto">Updated Task DTO</param>
        /// <returns>A bool stating if the record was updated sucesfully</returns>
        Task< bool > UpdateTaskAsync( TaskItemDto itemDto );
    }
}